name: hydra_dart
description: A light-weight library for building distributed applications such as microservices.
version: 0.0.1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  redis: 3.1.0
  uuid: 3.0.6
  shelf_router: ^1.0.0
