name: HydraDart
description: A light-weight library for building distributed applications such as microservices.
version: 0.0.1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  redis: any
  uuid: 3.0.6

